# -*- extra stuff goes here -*-
from servicedetails import IServiceDetails
from registeredresource import IRegisteredResource
from registeredservicecomponent import IRegisteredServiceComponent
from registeredservice import IRegisteredService
from resourcerequest import IResourceRequest
from servicecomponentrequest import IServiceComponentRequest
from servicerequest import IServiceRequest
from servicecomponentoffer import IServiceComponentOffer
from resourceoffer import IResourceOffer
from plan import IPlan
from environment import IEnvironment
from provider import IProvider
from person import IPerson
from resource import IResource
from center import ICenter
from community import ICommunity
from project import IProject
from service import IService
