# -*- coding: UTF-8 -*-
from zope import schema
from zope.interface import Interface


class ISettings(Interface):
    """ DPMT settings """

    accounting_url = schema.TextLine(
        title=u'Connection accounting server',
        description=u'Use http://host:port/path/to/domain',
        default=u'http://accounting.eudat.eu',
        required=True,
    )

    accounting_username = schema.TextLine(
        title=u'Username of the manager account on the accounting server',
        default=None,
    )

    accounting_password = schema.Password(
        title=u'Password of the manager account on the accounting server',
        default=None,
    )

    identifier_types = schema.List(
        title=u'Identifiers',
        description=u"Types of identifiers used to refer items.",
        required=False,
        default=[
            u'handle',
            u'doi',
            u'epic',
            u'orcid',
            u'rct_uid',
            u'dmp_online',
        ],
        missing_value=[],
        value_type=schema.TextLine(),
    )

    operating_systems = schema.List(
        title=u'Operating Systems',
        required=False,
        default=[
            u'SLES - SuSE Linux Enterprise Server from Novell',
            u'RHEL - Red Hat Enterprise Linux from Red Hat',
            u'Ubuntu - Ubuntu Server from Canonical',
            u'SL - Scientific Linux',
            u'Debian - Debian',
            u'CentOS - The Community Enterprise Operating System',
        ],
        missing_value=[],
        value_type=schema.TextLine(),
    )

    storage_types = schema.List(
        title=u'Storage types',
        required=False,
        default=[
            u'online',
            u'nearline',
            u'offline',
        ],
        missing_value=[],
        value_type=schema.TextLine(),
    )

    provider_types = schema.List(
        title=u'Provider Types',
        required=False,
        default=[
            u'generic',
            u'thematic',
        ],
        missing_value=[],
        value_type=schema.TextLine(),
    )

    provider_stati = schema.List(
        title=u'Provider Stati',
        required=False,
        default=[
            u'candidate',
            u'certified',
            u'closed',
            u'deprecated',
            u'suspended',
            u'uncertified',
        ],
        missing_value=[],
        value_type=schema.TextLine(),
    )

    country_names = schema.List(
        title=u'Country Names',
        required=False,
        default=[
            u'Afghanistan',
            u'Albania',
            u'Algeria',
            u'American Samoa',
            u'Andorra',
            u'Angola',
            u'Anguilla',
            u'Antarctica',
            u'Antigua Barbuda',
            u'Argentina',
            u'Armenia',
            u'Aruba',
            u'Australia',
            u'Austria',
            u'Azerbaijan',
            u'Bahamas',
            u'Bahrain',
            u'Bangladesh',
            u'Barbados',
            u'Belarus',
            u'Belgium',
            u'Belize',
            u'Benin',
            u'Bermuda',
            u'Bhutan',
            u'Bolivia',
            u'Bosnia Herzegovina',
            u'Botswana',
            u'Bouvet Island',
            u'Brazil',
            u'British Indian Ocean Territory',
            u'Brunei Darussalam',
            u'Bulgaria',
            u'Burkina Faso',
            u'Burundi',
            u'Cambodia',
            u'Cameroon',
            u'Canada',
            u'Cape Verde',
            u'Cayman Islands',
            u'Central African Republic',
            u'Chad',
            u'Chile',
            u'China',
            u'Christmas Island',
            u'Cocos (Keeling) Islands',
            u'Colombia',
            u'Comoros',
            u'Congo',
            u'Congo, Democratic Republic',
            u'Cook Islands',
            u'Costa Rica',
            u'Cote D\'Ivoire',
            u'Croatia',
            u'Cuba',
            u'Cyprus',
            u'Czech Republic',
            u'Denmark',
            u'Djibouti',
            u'Dominica',
            u'Dominican Republic',
            u'Ecuador',
            u'Egypt',
            u'El Salvador',
            u'Equatorial Guinea',
            u'Eritrea',
            u'Estonia',
            u'Ethiopia',
            u'Falkland Islands (Malvinas)',
            u'Faroe Islands',
            u'Fiji',
            u'Finland',
            u'France',
            u'French Guiana',
            u'French Polynesia',
            u'French Southern Territories',
            u'Gabon',
            u'Gambia',
            u'Georgia',
            u'Germany',
            u'Ghana',
            u'Gibraltar',
            u'Greece',
            u'Greenland',
            u'Grenada',
            u'Guadeloupe',
            u'Guam',
            u'Guatemala',
            u'Guinea',
            u'Guinea-Bissau',
            u'Guyana',
            u'Haiti',
            u'Heard Island Mcdonald Islands',
            u'Holy See (Vatican City State)',
            u'Honduras',
            u'Hong Kong',
            u'Hungary',
            u'Iceland',
            u'India',
            u'Indonesia',
            u'Iran, Islamic Republic',
            u'Iraq',
            u'Ireland',
            u'Israel',
            u'Italy',
            u'Jamaica',
            u'Japan',
            u'Jordan',
            u'Kazakhstan',
            u'Kenya',
            u'Kiribati',
            u'Korea, Democratic People\'s Republic',
            u'Korea, Republic',
            u'Kuwait',
            u'Kyrgyzstan',
            u'Lao People\'s Democratic Republic',
            u'Latvia',
            u'Lebanon',
            u'Lesotho',
            u'Liberia',
            u'Libyan Arab Jamahiriya',
            u'Liechtenstein',
            u'Lithuania',
            u'Luxembourg',
            u'Macao',
            u'Macedonia, Former Yugoslav Republic',
            u'Madagascar',
            u'Malawi',
            u'Malaysia',
            u'Maldives',
            u'Mali',
            u'Malta',
            u'Marshall Islands',
            u'Martinique',
            u'Mauritania',
            u'Mauritius',
            u'Mayotte',
            u'Mexico',
            u'Micronesia, Federated States',
            u'Moldova, Republic',
            u'Monaco',
            u'Mongolia',
            u'Montserrat',
            u'Morocco',
            u'Mozambique',
            u'Myanmar',
            u'Namibia',
            u'Nauru',
            u'Nepal',
            u'Netherlands',
            u'Netherlands Antilles',
            u'New Caledonia',
            u'New Zealand',
            u'Nicaragua',
            u'Niger',
            u'Nigeria',
            u'Niue',
            u'Norfolk Island',
            u'Northern Mariana Islands',
            u'Norway',
            u'Oman',
            u'Pakistan',
            u'Palau',
            u'Palestinian Territory, Occupied',
            u'Panama',
            u'Papua New Guinea',
            u'Paraguay',
            u'Peru',
            u'Philippines',
            u'Pitcairn',
            u'Poland',
            u'Portugal',
            u'Puerto Rico',
            u'Qatar',
            u'Reunion',
            u'Romania',
            u'Russian Federation',
            u'Rwanda',
            u'Saint Helena',
            u'Saint Kitts Nevis',
            u'Saint Lucia',
            u'Saint Pierre Miquelon',
            u'Saint Vincent Grenadines',
            u'Samoa',
            u'San Marino',
            u'Sao Tome Principe',
            u'Saudi Arabia',
            u'Senegal',
            u'Serbia Montenegro',
            u'Seychelles',
            u'Sierra Leone',
            u'Singapore',
            u'Slovakia',
            u'Slovenia',
            u'Solomon Islands',
            u'Somalia',
            u'South Africa',
            u'South Georgia South Sandwich Islands',
            u'Spain',
            u'Sri Lanka',
            u'Sudan',
            u'Suriname',
            u'Svalbard Jan Mayen',
            u'Swaziland',
            u'Sweden',
            u'Switzerland',
            u'Syrian Arab Republic',
            u'Taiwan, Province China',
            u'Tajikistan',
            u'Tanzania, United Republic',
            u'Thailand',
            u'Timor-Leste',
            u'Togo',
            u'Tokelau',
            u'Tonga',
            u'Trinidad Tobago',
            u'Tunisia',
            u'Turkey',
            u'Turkmenistan',
            u'Turks Caicos Islands',
            u'Tuvalu',
            u'Uganda',
            u'Ukraine',
            u'United Arab Emirates',
            u'United Kingdom',
            u'United States',
            u'United States Minor Outlying Islands',
            u'Uruguay',
            u'Uzbekistan',
            u'Vanuatu',
            u'Venezuela',
            u'Vietnam',
            u'Virgin Islands, British',
            u'Virgin Islands, U.S.',
            u'Wallis Futuna',
            u'Western Sahara',
            u'Yemen',
            u'Zambia',
        ],
        missing_value=[],
        value_type=schema.TextLine(),
    )

